version: 2

pipelines:
  - pipeline: 'shared'
    ref: '.*'
    stages:
      - stage: 'tox'
        tasks:
          - task: 'tox'
            steps:
              - action: 'gcr.io/action-containers/tox:3.0.0-2'
                args: ['-c', 'tox.ini']
      - stage: 'integration tests'
        tasks:
          - task: 'aloe'
            steps:
              - action: 'gcr.io/action-containers/medusa-it:1.0.0-2'
                entrypoint: "/bin/bash"
                args: ["run_integration_tests.sh"]
  - pipeline: 'master'
    ref: 'master'
    stages:
      - stage: 'old build debian package'
        tasks:
          - task: 'debbuild'
            steps:
              - action: 'gcr.io/action-containers/debian-packages:15'
                args: ['build', 'publish']
                envs:
                  RELEASE: stable
                  DISTRIBUTION: trusty
  - pipeline: 'master-bionic'
    ref: 'master-bionic'
    stages:
      - stage: 'build debian bionic package'
        tasks:
          - task: "Build and publish for Bionic"
            steps:
              - action: "gcr.io/action-containers/debian-packages-bionic:6"
                args: ["build", "publish"]
                envs:
                  RELEASE: stable
                  DISTRIBUTION: bionic
