version: 2

pipelines:
  - pipeline: 'shared'
    ref: '.*'
    stages:
      - stage: 'tox'
        tasks:
          - task: 'tox'
            steps:
              - action: 'gcr.io/action-containers/tox:3.0.0-2'
                args: ['-c', 'tox.ini']
      - stage: 'integration tests'
        tasks:
          - task: 'aloe'
            steps:
              - action: 'gcr.io/action-containers/medusa-it:1.0.0-2'
                entrypoint: "/bin/bash"
                args: ["run_integration_tests.sh"]
