version: 2

pipelines:
  - pipeline: 'shared'
    ref: '.*'
    stages:
      - stage: 'tox'
        tasks:
          - task: 'tox'
            steps:
              - action: 'gcr.io/action-containers/tox:3.0.0-2'
                args: ['-c', 'tox.ini']
      - stage: "Build package"
        tasks:
        - task: "Build for Bionic"
          steps:
          - action: "gcr.io/action-containers/debian-packages-bionic:5"
            args: ["build"]
            envs:
              DISTRIBUTION: bionic
  - pipeline: 'master'
    ref: 'master'
    stages:
      - stage: 'old build debian package'
        tasks:
          - task: 'debbuild'
            steps:
              - action: 'gcr.io/action-containers/debian-packages:15'
                args: ['build', 'publish']
                envs:
                  RELEASE: stable
                  DISTRIBUTION: trusty
      - stage: 'new build debian package'
        tasks:
          - task: "Build and publish for Bionic"
            steps:
              - action: "gcr.io/action-containers/debian-packages-bionic:5"
                args: ["build", "publish"]
                envs:
                  RELEASE: stable
                  DISTRIBUTION: bionic
