#!/bin/bash
set -e

if [ "$#" -ne 3 ]; then
  echo "Usage: $0 ROLE POD LOCATION" >&2
  echo "Example: $0 identity2 gew1 europe-west1" >&2
  exit 1
fi

set -x

# it's required to have the project created, this script does *not* do it
export OLD_GCP_PROJECT="medusa-backups"
export ROLE=$1
export POD=$2
export LOCATION=$3

export GCP_PROJECT="${ROLE}-medusa"
export SERVICE_ACCOUNT_NAME="${ROLE}-medusa"
export OLD_BUCKET_NAME="${ROLE}-medusa-backup"
export OLD_BUCKET_URL="gs://${OLD_BUCKET_NAME}"
export BUCKET_NAME="${ROLE}-backup"
export BUCKET_URL="gs://${BUCKET_NAME}"

# TTL for backups of this bucket
MAX_AGE=30

# Check if active project of gcloud matches the user-specified parameter
ACTIVE_PROJECT=$(gcloud config list 2>&1 | grep project | cut -d= -f2 | tr -d ' ')
if [ ${ACTIVE_PROJECT} != ${GCP_PROJECT} ]; then
    echo "ERROR: Chosen project ${GCP_PROJECT} is not the same as currently active gcloud project ${ACTIVE_PROJECT}"
    echo "Please run 'gcloud config set project ${GCP_PROJECT}' to make them match"
    exit 1
fi

# Check if the role exists and possibly create it
ROLE_EXISTS=$(gcloud iam roles list --project ${GCP_PROJECT} | grep title | grep -c MedusaStorageAgent || true)
if [ ${ROLE_EXISTS} -eq 1 ]; then
    echo "Role MedusaStorageAgent already exists in project ${GCP_PROJECT}, not creating again"
else
    echo "Role MedusaStorageAgent does not exist in project ${GCP_PROJECT}, creating ..."
    gcloud iam roles create MedusaStorageAgent \
        --project ${GCP_PROJECT} \
        --stage GA \
        --title MedusaStorageAgent \
        --description "Custom role for Medusa for accessing GCS safely" \
        --permissions storage.buckets.get,storage.buckets.getIamPolicy,storage.objects.create,storage.objects.delete,storage.objects.get,storage.objects.getIamPolicy,storage.objects.list
fi

#Create bucket
echo "Creating GCP bucket ${BUCKET_NAME}"
# --retention 30d prevents unwanted deletes for 30 days
gsutil mb -p ${GCP_PROJECT} -c regional -l ${LOCATION} ${BUCKET_URL}

# Add TTL to the bucket
cat <<EOF >life.json
{
  "rule":
  [
    {
      "action": {"type": "Delete"},
      "condition": {"age": ${MAX_AGE}}
    }
  ]
}
EOF

gsutil lifecycle set life.json ${BUCKET_URL} && rm life.json
echo

#Service account
echo "Setting up service account"
gcloud --project ${GCP_PROJECT} iam service-accounts create ${SERVICE_ACCOUNT_NAME} --display-name ${SERVICE_ACCOUNT_NAME}
gcloud --project ${GCP_PROJECT} iam service-accounts keys create ${SERVICE_ACCOUNT_NAME}.json --iam-account=${SERVICE_ACCOUNT_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com
echo

#Add credentials to celo
echo "Pushing service account's secret to CELO. Will ask for password"
(curl --fail -u ${USER} -X POST https://celo.spotify.net/role/${ROLE}/production -d key='medusa::credentials' --data-urlencode secret@${SERVICE_ACCOUNT_NAME}.json && rm ${SERVICE_ACCOUNT_NAME}.json) || exit $?
echo

#Grant permissions
echo "Granting bucket permissions to the service account"
gsutil iam set <(gsutil iam get ${BUCKET_URL} | jq ".bindings += [{\"members\":[\"serviceAccount:${SERVICE_ACCOUNT_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com\"],\"role\":\"projects/${GCP_PROJECT}/roles/MedusaStorageAgent\"}]") ${BUCKET_URL}
echo

echo "Transition setup done. Please make sure you changed the bucket in use for ${ROLE} in hiera-data/role/${ROLE}/${POD}.yaml from ${OLD_BUCKET_NAME} to ${BUCKET_NAME}"
