version: 2
jobs:
  build:
    docker:
      - image: thelastpickle/ubuntu:18.0.4-sudo

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}

      - run:
          name: run tox
          command: |
            python3 -m venv venv
            . venv/bin/activate
            tox
      - run:
          name: run integration tests
          command: |
            . venv/bin/activate
            ./run_integration_tests.sh
